librocr/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('principal.urls')),
    path('libros/', include('libros.urls')),
    path('ocr/', include('ocr.urls')),
    path('admin/', admin.site.urls),
]

libros/urls.py
from django.urls import path

from . import views


app_name = 'libros'
urlpatterns = [
    path('', views.todos, name='todos'),
    path('<int:isbn>', views.libro, name='libro'),
    path('<int:isbn>/<int:numero>', views.pagina, name='pagina'),
    path('editar/<int:isbn>', views.editar_libro, name='editar_libro'),
    path('editar/<int:isbn>/<int:numero>', views.editar_pagina, name='editar_pagina'),
    path('buscar', views.buscar_libro, name="buscar")
]

ocr/urls.py
from django.urls import path

from . import views


app_name = 'ocr'
urlpatterns = [
    path('rapido', views.rapido, name='rapido'),
    path('completo', views.completo, name='completo'),
]

principal/urls.py
from django.urls import path
from . import views


app_name = 'principal'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_session, name='login'),
    path('logout', views.logout_session, name='logout')
]

libros/models.py
from django.db import models


class Libro(models.Model):
    isbn = models.CharField(max_length=24, primary_key=True, default='x')
    titulo = models.CharField(max_length=120, default='x')
    autor = models.CharField(max_length=120, default='x')
    anio = models.CharField(max_length=4, default='x')

    procesado = models.BooleanField(default=False)
    estado = models.BooleanField(default=True)

    def cantidad_paginas(self):
        return len(Pagina.objects.filter(libro=self))

    def __str__(self):
        return self.isbn + ' - ' + self.titulo


class Pagina(models.Model):
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    numero = models.IntegerField()
    imagen = models.ImageField(upload_to='paginas')
    texto = models.CharField(max_length=5000, blank=True, default='')

    def anterior(self):
        if self.numero > 1:
            return self.numero - 1
        return None

    def siguiente(self):
        if self.numero < len(Pagina.objects.filter(libro=self.libro)):
            return self.numero + 1
        return None

    def navegacion(self):
        lista = None
        if 1 < self.numero < len(Pagina.objects.filter(libro=self.libro)):
            lista = [i for i in range(self.numero - 1, self.numero + 2)]
        elif self.numero == 1:
            lista = [1, 2, 3]
        elif self.numero == len(Pagina.objects.filter(libro=self.libro)):
            lista = [i for i in range(self.numero - 2, self.numero + 1)]
        return lista

    def __str__(self):
        return '{libro} - pagina {numpagina}'.format(
            libro=self.libro.titulo,
            numpagina=self.numero
        )

libros/forms.py
from django import forms


class ActualizarLibroForm(forms.Form):
    isbn_libro = forms.CharField(label="ISBN del libro", required=True)
    titulo_libro = forms.CharField(label="Nombre del libro", required=True)
    autor_libro = forms.CharField(label="Autor del libro", required=True)
    anio_libro = forms.CharField(label="Año de publicación", required=True)


class ActualizarPaginaForm(forms.Form):
    texto_pagina = forms.CharField(
        label="Contenido de la página", required=True)


class BusquedaLibroForm(forms.Form):
    busqueda = forms.CharField(label="Busqueda", required=True)

libros/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.contrib.auth.decorators import login_required

from principal.views import get_name
from .models import Libro, Pagina
from .forms import ActualizarLibroForm, ActualizarPaginaForm, BusquedaLibroForm


# Funciones auxiliares
def get_libro_or_404(isbn):

    try:
        _libro = Libro.objects.get(isbn=isbn)
        return _libro
    except Libro.DoesNotExist:
        raise Http404


# Vistas
@login_required
def todos(request):

    libros = Libro.objects.filter(estado=True)
    name = get_name(request)
    context = {
        'libros': libros,
        'name': name
    }
    return render(request, 'libros/todos.html', context)


@login_required
def libro(request, isbn, altcontext={}):

    libro_object = get_object_or_404(Libro, isbn=isbn)
    name = get_name(request)
    context = {
        'libro': libro_object,
        'name': name
        }
    context.update(altcontext)
    return render(request, 'libros/libro.html', context)


@login_required
def pagina(request, isbn, numero, altcontext={}):

    _libro = get_libro_or_404(isbn)
    pagina_object = get_object_or_404(Pagina, libro=_libro, numero=numero)
    name = get_name(request)

    context = {
        'libro': _libro,
        'pagina': pagina_object,
        'name': name
        }
    context.update(altcontext)

    return render(
        request,
        'libros/pagina.html',
        context
    )


@login_required
def editar_libro(request, isbn):

    actualizo = False

    if request.method == 'POST':
        form = ActualizarLibroForm(request.POST)

        if form.is_valid():
            _libro = get_libro_or_404(isbn=form.cleaned_data['isbn_libro'])
            _libro.titulo = form.cleaned_data['titulo_libro']
            _libro.autor = form.cleaned_data['autor_libro']
            _libro.anio = form.cleaned_data['anio_libro']
            _libro.save()
            response = libro(request, isbn, {'actualizo': True})
            return response

    _libro = get_object_or_404(Libro, isbn=isbn)
    name = get_name(request)
    context = {
        'libro': _libro,
        'actualizo': actualizo,
        'name': name
        }
    return render(
        request,
        'libros/editar_libro.html',
        context)


@login_required
def editar_pagina(request, isbn, numero):

    if request.method == 'POST':
        _form = ActualizarPaginaForm(request.POST)
        
        if _form.is_valid():
            _libro = get_libro_or_404(isbn)
            _pagina = get_object_or_404(Pagina, libro=_libro, numero=numero)

            _pagina.texto = _form.cleaned_data['texto_pagina']
            _pagina.save()

            response = pagina(request, isbn, numero, {'actualizo': True})
            return response

    _libro = get_libro_or_404(isbn)
    _pagina = get_object_or_404(Pagina, libro=_libro, numero=numero)
    name = get_name(request)
    context = {
        'libro': _libro,
        'pagina': _pagina,
        'name': name
    }
    return render(request, 'libros/editar_pagina.html', context)


@login_required
def buscar_libro(request):

    _form = BusquedaLibroForm(request.GET)
    if _form.is_valid():

        busqueda = request.GET['busqueda']
        _paginas = Pagina.objects.filter(texto__icontains=busqueda)
        resultados = []

        for _pag in _paginas:
            resultados.append(
                {
                    'libro': _pag.libro.titulo,
                    'isbn': _pag.libro.isbn,
                    'pagina': _pag.numero
                })

        return render(
            request,
            'libros/buscar_libro.html',
            {
                'resultados': resultados,
                'name': get_name(request)
            })

    return render(
        request,
        'libros/buscar_libro.html',
        {'name': get_name(request)}
    )

templates/libros/buscar_libro.html
{% extends '../base.html' %}

{% block title %}Busqueda{% endblock %}

{% block content %}
<div class="main-content">
	<section class="section">
		<div class="section-header">
			<h1>Busqueda</h1>
		</div>

		<div class="section-body">
			{% if resultados %}
				{% regroup resultados by libro as libros %}
		        {% for libro in libros %}
		        	<div class="card col-12 col-md-6 col-lg-6">
		        		<div class="card-header">
		        			<h4>{{ libro.grouper }}</h4>
		        		</div>
		        		<div class="card-body">
							<ul>
							{% for pagina in libro.list %}
								<li>
									<a href="{% url 'libros:pagina' pagina.isbn pagina.pagina %}">
										Pagina {{ pagina.pagina }}
									</a>
								</li>
							{% endfor %}
							</ul>
		        		</div>
		        	</div>
		        {% endfor %}
			{% else %}
				<div class="card">
	        		<div class="card-header">
	        			<h4>Sin resultados</h4>
	        		</div>
	        		<div class="card-body">
	        			No existen textos con el término que está buscando.
	        		</div>
	        		<div class="card-footer text-center">
	        			<a href="{% url 'principal:index' %}" class="btn btn-icon btn-primary">
	                        <i class="fas fa-home"></i> Ir a inicio
	                    </a>
	        		</div>
	        	</div>
	        {% endif %}
        </div> 
    </section>
</div>
{% endblock %}

templates/libros/editar_libro.html
{% extends '../base.html' %}

{% block title %}Editar libro - {{ libro.titulo }}{% endblock %}

{% block content %}
<div class="main-content">
	<section class="section">
		<div class="section-header">
			<h1>Editar libro</h1>
		</div>
		<div class="section-body">
            
            <form method="POST" action="{% url 'libros:editar_libro' libro.isbn %}">
            {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>ISBN</label>
                                <input type="text" name="isbn_libro" class="form-control" readonly=""  value="{{ libro.isbn }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Título</label>
                                <input type="text" name="titulo_libro" class="form-control" value="{{ libro.titulo }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Autor</label>
                                <input type="text" name="autor_libro" class="form-control" value="{{ libro.autor }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Año de publicación</label>
                                <input type="numeric" name="anio_libro" class="form-control" value="{{ libro.anio }}">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button type="submit" class="btn btn-icon btn-primary">
                            <i class="fas fa-check"></i> Actualizar
                        </button>
                        <a href="{% url 'libros:libro' libro.isbn %}" class="btn btn-icon btn-warning">
                            <i class="fas fa-undo"></i> Cancelar
                        </a>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
{% endblock %}

templates/libros/editar_pagina.html
{% extends '../base.html' %}

{% load static %}

{% block title %}{{ libro.titulo }} - Editar pagina {{ pagina.numero }}{% endblock %}

{% block additionalcss %}
<link rel="stylesheet" href="{% static 'assets/modules/summernote/summernote-bs4.css' %}">
<link rel="stylesheet" href="{% static 'assets/modules/jquery-selectric/selectric.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
	<section class="section">
		<div class="section-header">
			<h1>Editar pagina</h1>
		</div>

		<div class="section-body">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<h4>{{ libro.titulo }} | pagina {{ pagina.numero }}</h4>
						</div>
						<form method="POST" action="{% url 'libros:editar_pagina' libro.isbn pagina.numero %}">
							{% csrf_token %}
							<div class="card-body">
								<textarea name="texto_pagina" class="summernote-simple">
									{{ pagina.texto|linebreaks }}
								</textarea>
							</div>
							<div class="card-footer text-right">
								<button type="submit" class="btn btn-icon btn-primary">
								<i class="fas fa-check"></i> Actualizar
								</button>
								<a href="{% url 'libros:pagina' libro.isbn pagina.numero %}" class="btn btn-icon btn-warning">
									<i class="fas fa-undo"></i> Cancelar
								</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
{% endblock %}

{% block additionaljs %}
<script src="{% static 'assets/modules/summernote/summernote-bs4.js' %}"></script>
<script src="{% static 'assets/modules/jquery-selectric/jquery.selectric.min.js' %}"></script>
{% endblock %}

templates/libros/libro.html
{% extends '../base.html' %}

{% block title %}{{ libro.titulo }} - Informacion{% endblock %}

{% block content %}
<div class="main-content">
	<section class="section">
		<div class="section-header">
			<h1>Informacion de libro</h1>
		</div>
		<div class="section-body">
            {% if actualizo %}
                <div class="alert alert-success alert-dismissible show fade">
                    <div class="alert-body">
                        <button class="close" data-dismiss="alert"><span>×</span></button>
                        El libro se ha actualizado correctamente. 
                    </div>
                </div>
            {% endif %}
			<div class="card">
				<div class="card-header">
                    <h4>{{ libro.titulo }}</h4>
				</div>
				<div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>ISBN</label>
                            <input type="text" class="form-control-plaintext" readonly="" value="{{ libro.isbn }}">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Autor</label>
                            <input type="text" class="form-control-plaintext" readonly="" value="{{ libro.autor }}">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Año</label>
                            <input type="text" class="form-control-plaintext" readonly="" value="{{ libro.anio }}">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Cantidad de paginas</label>
                            <input type="text" class="form-control-plaintext" readonly="" value="{{ libro.cantidad_paginas }}">
                        </div>
                    </div>
				</div>
                <div class="card-footer text-right">
                    <a href="{% url 'libros:pagina' libro.isbn 1 %}" class="btn btn-icon btn-primary">
                        <i class="fas fa-book-open"></i> Ver
                    </a>
                    <a href="{% url 'libros:editar_libro' libro.isbn %}" class="btn btn-icon btn-warning">
                        <i class="fas fa-edit"></i> Editar
                    </a>
                    <a href="{% url 'libros:todos' %}" class="btn btn-icon btn-secondary">
                        <i class="fas fa-book"></i> Volver
                    </a>
                </div>
			</div>
		</div>
	</section>
</div>
{% endblock %}

templates/libros/pagina.html
{% extends '../base.html' %}

{% block title %}{{ libro.titulo }} - Pagina {{ pagina.numero }}{% endblock %}

{% block content %}

<div class="main-content">
	<section class="section">
		<div class="section-header">
            <h1>Vista de libro</h1>
            <div class="section-header-breadcrumb text-dark-all">
                <div class="breadcrumb-item">
                    <a href="{% url 'libros:editar_pagina' libro.isbn pagina.numero %}">
                        <i class="fas fa-edit"></i> Editar
                    </a>
                </div>
                <div class="breadcrumb-item">
                    <a href="{% url 'libros:libro' libro.isbn %}">
                        <i class="fas fa-undo"></i> Volver
                    </a>
                </div>
            </div>
		</div>

		<div class="section-body">
            {% if actualizo %}
                <div class="alert alert-success alert-dismissible show fade">
                    <div class="alert-body">
                        <button class="close" data-dismiss="alert"><span>×</span></button>
                        La página se ha actualizado correctamente. 
                    </div>
                </div>
            {% endif %}
			<div class="card">
                <div class="card-header">
                    <h4>{{libro.titulo}} - pagina {{pagina.numero}}</h4>
                </div>
                <div class="card-body">
                    {% autoescape off %}
                        {{ pagina.texto|linebreaks }}
                    {% endautoescape %}
                </div>
                <div class="card-footer">
                    <nav aria-label="...">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not pagina.anterior %}disabled{% endif %}">
                                <a class="page-link" href="{% if pagina.anterior %}{% url 'libros:pagina' libro.isbn pagina.anterior %}{% else %}#{% endif %}" tabindex="-1">Anterior</a>
                            </li>

                            {% for numero in pagina.navegacion %}
                                {% if numero == pagina.numero %}
                                <li class="page-item active">
                                    <a class="page-link" href="{% url 'libros:pagina' libro.isbn numero %}">{{ numero }}<span class="sr-only">(current)</span></a>
                                </li>
                                {% else %}
                                <li class="page-item"><a class="page-link" href="{% url 'libros:pagina' libro.isbn numero %}">{{ numero }}</a></li>
                                {% endif %}
                            {% endfor %}
                            <li class="page-item {% if not pagina.siguiente %}disabled{% endif %}">
                                <a class="page-link" href="{% if pagina.siguiente %}{% url 'libros:pagina' libro.isbn pagina.siguiente %}{% else %}#{% endif %}">Siguiente</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

templates/libros/todos.html
{% extends '../base.html' %}
{% load static %}
{% block additionalcss %}

<link rel="stylesheet" href="{% static 'assets/modules/datatables/datatables.min.css' %}">
<link rel="stylesheet"
    href="{% static 'assets/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/modules/datatables/Select-1.2.4/css/select.bootstrap4.min.css' %}">
{% endblock %}

{% block title %}Todos los libros{% endblock %}

{% block content %}
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Libros</h1>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- <div class="card-header">
                            <h4>Libros</h4>
                        </div> -->
                        <div class="card-body">
                            <div class="table-responsive">
                                <table data-order='[[ 0, "asc" ]]' class="table table-striped" id="libros-table">
                                    <thead>
                                        <tr>
                                            <!-- <th class="text-center"> -->
                                            <th>Titulo</th>
                                            <th>Autor</th>
                                            <th>Año de publicación</th>
                                            <th>Abrir</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for libro in libros %}
                                        <tr>
                                            <td>{{ libro.titulo }}</td>
                                            <td>{{ libro.autor }}</td>
                                            <td>{{ libro.anio }}</td>
                                            {% if libro.procesado %}
                                                <td><a href="{% url 'libros:libro' libro.isbn %}" class="btn btn-info btn-sm">Ver libro</a></td>
                                            {% else %}
                                                <td><a href="#" class="disabled btn btn-warning btn-sm">Procesando</a></td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block additionaljs %}
<script src="{% static 'assets/modules/datatables/datatables.min.js' %}"></script>
<script src="{% static 'assets/modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'assets/modules/datatables/Select-1.2.4/js/dataTables.select.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#libros-table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>
{% endblock %}