librocr/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('principal.urls')),
    path('libros/', include('libros.urls')),
    path('ocr/', include('ocr.urls')),
    path('admin/', admin.site.urls),
]

libros/urls.py
from django.urls import path

from . import views


app_name = 'libros'
urlpatterns = [
    path('', views.todos, name='todos'),
    path('<int:isbn>', views.libro, name='libro'),
    path('<int:isbn>/<int:numero>', views.pagina, name='pagina'),
    path('editar/<int:isbn>', views.editar_libro, name='editar_libro'),
    path('editar/<int:isbn>/<int:numero>', views.editar_pagina, name='editar_pagina'),
    path('buscar', views.buscar_libro, name="buscar")
]

ocr/urls.py
from django.urls import path

from . import views


app_name = 'ocr'
urlpatterns = [
    path('rapido', views.rapido, name='rapido'),
    path('completo', views.completo, name='completo'),
]

principal/urls.py
from django.urls import path
from . import views


app_name = 'principal'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_session, name='login'),
    path('logout', views.logout_session, name='logout')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>{% block title %}{% endblock %} - ROCBOOK</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/modules/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/fontawesome/css/all.min.css' %}">

    <!-- Specific Page CSS files -->
    {% block additionalcss %}{% endblock %}

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
</head>

<body>
    <div id="app">
        <div class="main-wrapper">
            <div class="navbar-bg"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                <form action="{% url 'libros:buscar' %}" method="GET" class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i
                                    class="fas fa-bars"></i></a></li>
                        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                                    class="fas fa-search"></i></a></li>
                    </ul>
                    <div class="search-element">
                            <input class="form-control" name="busqueda" type="search" placeholder="Buscar" aria-label="Search">
                            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown"><a href="#" data-toggle="dropdown"
                            class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="{% static 'assets/img/avatar/avatar-4.png' %}" width="30"
                                class="rounded-circle mr-1">
                            <div class="d-sm-none d-lg-inline-block">{{ name }}</div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="{% url 'principal:logout' %}" class="dropdown-item has-icon text-danger">
                                <i class="fas fa-sign-out-alt"></i> Salir
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>

            <div class="main-sidebar">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a href="{% url 'principal:index' %}">ROCBOOK</a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a href="{% url 'principal:index' %}">RB</a>
                    </div>
                    <ul class="sidebar-menu">
                        <li><a class="nav-link" href="{% url 'principal:index' %}">
                                <i class="fas fa-home"></i><span>Inicio</span>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'libros:todos' %}">
                                <i class="fas fa-book"></i><span>Libros</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown">
                                <i class="fas fa-eye"></i><span>ROC</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link" href="{% url 'ocr:rapido' %}">Simple</a></li>
                                <li><a class="nav-link" href="{% url 'ocr:completo' %}">Libro completo</a></li>
                            </ul>
                        </li>
                    </ul>
                   {% comment %} <div class="mt-4 mb-4 p-3 hide-sidebar-mini footer">
                        <a href="#" class="btn btn-primary btn-lg btn-block btn-icon-split">
                            <i class="fas fa-info"></i> Acerca de
                        </a>
                    COLOCAR AL FONDO DEL SIDEBAR
                    </div> {% endcomment %}
                </aside>
            </div>

            <!-- Main Content -->
            {% block content %}{% endblock %}
            
            <footer class="main-footer">
                <div class="footer-left">
                    Copyright © 2019 <div class="bullet"></div> UNEFA
                </div>
                <div class="footer-right">
                    Biblioteca
                </div>
            </footer>
        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="{% static 'assets/modules/jquery.min.js' %}"></script>
    <script src="{% static 'assets/modules/popper.js' %}"></script>
    <script src="{% static 'assets/modules/tooltip.js' %}"></script>
    <script src="{% static 'assets/modules/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'assets/modules/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/stisla.js' %}"></script>


    <!-- Page Specific JS Files -->
    {% block additionaljs %}{% endblock %}

    <!-- Template JS File -->
    <script src="{% static 'assets/js/scripts.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>

</html>